Add header in index.html + styles, scripts, images for website
FelisssTattoo/FelisssTattooSite pull request #5
Opened 2023-04-26 09:59 UTC by in-siders17

2023-04-26 16:06 UTC, dindin28 requested changes

2023-04-26 16:06 UTC, dindin28 commented on index.html
> +		<link href="styles/css(1)" rel="stylesheet">
Can it be merged in single css?

2023-04-26 16:06 UTC, dindin28 commented on index.html
> +	<meta http-equiv="origin-trial" content="A727AcAeLCei/ZogJHBlJUS63SxP6AeIROo7qXrkjrxkoxBu0eSSmypAHmGYwk4HjBMQp5nxCFODzfVnUIe31AQAAAB7eyJvcmlnaW4iOiJodHRwczovL3d3dy5nb29nbGV0YWdtYW5hZ2VyLmNvbTo0NDMiL
check if "f(1).txt" can be renamed to "f(1).txt"

2023-04-26 16:06 UTC, dindin28 commented on index.html
> +									<a href="https://www.tattoo-lamarch.studio/#sec1" class="nav-ul-li-a">Про нас</a>
Make relative page "/#about-us"

Check what better naming for html classes
"about-us" or "about_us"

2023-04-26 16:06 UTC, dindin28 commented on index.html
> +									<a href="https://www.tattoo-lamarch.studio/#sec4" class="nav-ul-li-a">Команда</a>
Make relative page "/#our-team"

2023-04-26 16:06 UTC, dindin28 commented on index.html
> +									<a href="https://www.tattoo-lamarch.studio/#sec6" class="nav-ul-li-a">Контакти</a>
Make relative page "/#contacts"

2023-04-26 16:06 UTC, dindin28 commented on index.html
> +									TATTOO LAMARCH STUDIO
FELISSS TATTOO

2023-04-26 16:06 UTC, dindin28 commented on index.html
> +								<a href="tel:+380940000003"><span>Тел.</span> +38 (094) 000-000-3</a>
tel:+380973074604 
+38 (094) 000-000-3 -> 097 307 46 04

2023-04-26 16:06 UTC, dindin28 commented on index.html
> +								<div><span>Рабочі години:</span> 10:00 - 22:00</div>
8:00 - 18:00

2023-04-27 15:22 UTC, in-siders17 commented on index.html
> +		<meta name="description" content="Самый молодёжный тату салон в городе. LUXURY комфорт и атмосфера.
Complete

2023-04-27 15:22 UTC, in-siders17 commented on index.html
> +		<meta name="keywords" content="tattoo lamarch studio, тату винница, винница тату, ламарч, тату ламарч винница, тату ламарч">
Complete

2023-04-27 15:24 UTC, in-siders17 commented on index.html
> +		<link rel="icon" href="https://www.tattoo-lamarch.studio/tattoo.ico">
edited complete

2023-04-27 15:24 UTC, in-siders17 commented on index.html
> +		<title>TATTOO LAMARCH STUDIO</title>
edited compliete

2023-05-02 09:11 UTC, merged